#!/usr/bin/env python
"""
Stage C Training Script: Counterfactual MoE Decoder

This script trains the MoE decoder head for counterfactual generation.
The encoder and existing 12 heads are FROZEN - only the decoder trains.

Design Principles:
    1. Colab-friendly: Designed for 18-hour runtime limits
    2. Resume-robust: Saves frequently, easy to resume from any checkpoint
    3. Memory-efficient: Gradient checkpointing, bf16, optimized batch sizes
    4. Production-ready: Proper logging, metrics, error handling

Training Data:
    - Generated by: scripts/agents/counterfactual_data_generator.py
    - Prepared by: scripts/agents/prepare_decoder_training_data.py
    - Location: data/counterfactual/training/
        - samples.jsonl: Text data
        - embeddings.h5: Precomputed encoder embeddings (768-dim)
        - train_val_split.json: 95/5 split indices

Architecture (~420M trainable params):
    - Encoder: 155M params (FROZEN)
    - Existing 12 heads: ~10M params (FROZEN)
    - Decoder: 8 layers (2 dense + 6 MoE), ~420M params (TRAINABLE)
    - 8 experts per MoE layer, top-2 routing
    - 1 shared expert (always active)

Usage:
    # Standard training
    python scripts/train_stage_c.py --config configs/training/multitask/stage_c_decoder.yaml

    # Resume from checkpoint (critical for Colab)
    python scripts/train_stage_c.py \
        --config configs/training/multitask/stage_c_decoder.yaml \
        --resume_from_checkpoint checkpoints/ultrabert-gen-decoder-v1/checkpoint-5000

    # Debug mode (small batches, fast epochs)
    python scripts/train_stage_c.py \
        --config configs/training/multitask/stage_c_decoder.yaml \
        --debug

    # Find latest checkpoint automatically
    python scripts/train_stage_c.py \
        --config configs/training/multitask/stage_c_decoder.yaml \
        --auto_resume

Environment:
    - GPU: Colab T4/V100 (16GB+), A100 preferred (40GB)
    - RAM: 16GB+ (32GB recommended)
    - Disk: ~5GB for checkpoints

Output:
    - checkpoints/ultrabert-gen-decoder-v1/: Training checkpoints (saved every 500 steps)
    - outputs/ultrabert-gen-decoder-v1/: Final model, configs, eval results
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import re
import signal
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

import torch
import yaml
from transformers import AutoTokenizer, TrainingArguments, set_seed

# Add project root to path if running as script
project_root = Path(__file__).parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

# Configure logging
logging.basicConfig(
    format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)


# =============================================================================
# Signal Handling for Colab (graceful shutdown on interrupt)
# =============================================================================

_TRAINER_INSTANCE = None
_INTERRUPT_RECEIVED = False


def _signal_handler(signum, frame):
    """Handle interrupt signal - save checkpoint before exit."""
    global _INTERRUPT_RECEIVED
    if _INTERRUPT_RECEIVED:
        logger.warning("Second interrupt received, forcing exit...")
        sys.exit(1)

    _INTERRUPT_RECEIVED = True
    logger.warning("=" * 60)
    logger.warning("INTERRUPT RECEIVED - Saving checkpoint before exit...")
    logger.warning("=" * 60)

    if _TRAINER_INSTANCE is not None:
        try:
            # Save current checkpoint
            _TRAINER_INSTANCE.save_model()
            _TRAINER_INSTANCE.save_state()
            logger.info("Checkpoint saved successfully!")
            logger.info(f"Resume with: --resume_from_checkpoint {_TRAINER_INSTANCE.args.output_dir}")
        except Exception as e:
            logger.error(f"Failed to save checkpoint: {e}")

    sys.exit(0)


# Register signal handlers
signal.signal(signal.SIGINT, _signal_handler)
signal.signal(signal.SIGTERM, _signal_handler)


# =============================================================================
# Configuration Management
# =============================================================================


def load_config(config_path: str | Path) -> dict[str, Any]:
    """Load configuration from YAML file."""
    config_path = Path(config_path)
    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")

    with open(config_path, encoding="utf-8") as f:
        config = yaml.safe_load(f)

    logger.info(f"Loaded config from {config_path}")
    return config


def apply_overrides(config: dict[str, Any], overrides: list[str]) -> dict[str, Any]:
    """Apply command-line overrides to config."""
    for override in overrides:
        if "=" not in override:
            continue
        key, value = override.split("=", 1)
        key = key.lstrip("-")
        keys = key.split(".")

        # Navigate to the right place in config
        current = config
        for k in keys[:-1]:
            if k not in current:
                current[k] = {}
            current = current[k]

        # Parse value type
        try:
            parsed_value = yaml.safe_load(value)
        except Exception:
            parsed_value = value

        current[keys[-1]] = parsed_value
        logger.info(f"Override: {key} = {parsed_value}")

    return config


def find_latest_checkpoint(checkpoint_dir: str | Path) -> str | None:
    """
    Find the latest checkpoint in a directory.

    Useful for auto-resuming after Colab disconnection.

    Args:
        checkpoint_dir: Directory containing checkpoint-XXXX folders

    Returns:
        Path to latest checkpoint, or None if no checkpoints found
    """
    checkpoint_dir = Path(checkpoint_dir)
    if not checkpoint_dir.exists():
        return None

    # Find all checkpoint folders
    checkpoint_pattern = re.compile(r"checkpoint-(\d+)$")
    checkpoints = []

    for folder in checkpoint_dir.iterdir():
        if folder.is_dir():
            match = checkpoint_pattern.match(folder.name)
            if match:
                step = int(match.group(1))
                checkpoints.append((step, folder))

    if not checkpoints:
        return None

    # Return path to latest checkpoint
    latest = max(checkpoints, key=lambda x: x[0])
    return str(latest[1])


# =============================================================================
# Argument Parsing
# =============================================================================


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Train MoE decoder for counterfactual generation (Stage C)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "--config",
        type=str,
        default="configs/training/multitask/stage_c_decoder.yaml",
        help="Path to training configuration file",
    )

    parser.add_argument(
        "--resume_from_checkpoint",
        type=str,
        default=None,
        help="Path to checkpoint directory to resume from",
    )

    parser.add_argument(
        "--auto_resume",
        action="store_true",
        help="Automatically find and resume from latest checkpoint",
    )

    parser.add_argument(
        "--output_dir",
        type=str,
        default=None,
        help="Override output directory from config",
    )

    parser.add_argument(
        "--checkpoint_dir",
        type=str,
        default=None,
        help="Override checkpoint directory from config",
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Random seed (overrides config)",
    )

    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug mode (smaller batches, more logging, faster epochs)",
    )

    parser.add_argument(
        "--dry_run",
        action="store_true",
        help="Validate config and data loading without training",
    )

    parser.add_argument(
        "--local_rank",
        type=int,
        default=-1,
        help="Local rank for distributed training",
    )

    # Accept additional overrides as key=value pairs
    parser.add_argument(
        "overrides",
        nargs="*",
        help="Config overrides in format key.subkey=value",
    )

    return parser.parse_args()


# =============================================================================
# Model Initialization
# =============================================================================


def load_base_model(config: dict[str, Any], device: str = "cuda"):
    """
    Load the base model from Stage B checkpoint.

    Args:
        config: Configuration dictionary
        device: Device to load model on

    Returns:
        ModernBertMultiTaskModel with encoder and existing heads
    """
    from modeling_studio.models.modernbert_multitask import ModernBertMultiTaskModel

    model_config = config.get("model", {})
    checkpoint_path = model_config.get("checkpoint_path")

    if not checkpoint_path:
        raise ValueError("model.checkpoint_path is required in config")

    checkpoint_path = Path(checkpoint_path)
    if not checkpoint_path.exists():
        raise FileNotFoundError(f"Checkpoint not found: {checkpoint_path}")

    logger.info(f"Loading base model from {checkpoint_path}")

    # Load using checkpoint loader
    model = ModernBertMultiTaskModel.load_checkpoint(
        checkpoint_path=str(checkpoint_path),
        device=device,
    )

    logger.info(f"Loaded model with capabilities: {[c.value for c in model.capabilities]}")
    logger.info(f"Total params: {sum(p.numel() for p in model.parameters()):,}")

    return model


def initialize_decoder_head(
    model,
    config: dict[str, Any],
    tokenizer=None,
):
    """
    Initialize a decoder head and add it to the model.

    Supports two decoder types:
        - "moe": MoE decoder (~420M params, requires large training data)
        - "gpt2": GPT-2 based decoder (~355M params, pre-trained, edge-friendly)

    The decoder type is selected via config["decoder"]["type"]. Default is "moe".

    Args:
        model: The base multi-task model
        config: Configuration dictionary with decoder settings
        tokenizer: Optional tokenizer to get vocab_size and special tokens

    Returns:
        The model with decoder head added
    """
    decoder_config_dict = config.get("decoder", {})
    decoder_type = decoder_config_dict.get("type", "moe").lower()

    if decoder_type == "gpt2":
        return _initialize_gpt2_decoder(model, config, tokenizer)
    elif decoder_type == "moe":
        return _initialize_moe_decoder(model, config, tokenizer)
    else:
        raise ValueError(f"Unknown decoder type: {decoder_type}. Must be 'moe' or 'gpt2'.")


def _initialize_gpt2_decoder(
    model,
    config: dict[str, Any],
    tokenizer=None,
):
    """
    Initialize GPT-2 based decoder head.

    This uses a pre-trained GPT-2 model with prefix injection for
    encoder-decoder connection. Designed for edge deployment.
    """
    from modeling_studio.data.labels import Capability
    from modeling_studio.models.decoder_gpt2_config import GPT2DecoderConfig
    from modeling_studio.models.decoder_gpt2 import GPT2DecoderHead

    decoder_config_dict = config.get("decoder", {})

    # Get vocab size and special tokens from tokenizer if available
    if tokenizer is not None:
        vocab_size = len(tokenizer)
        pad_token_id = tokenizer.pad_token_id if tokenizer.pad_token_id is not None else 0
        bos_token_id = tokenizer.bos_token_id if tokenizer.bos_token_id is not None else tokenizer.cls_token_id
        eos_token_id = tokenizer.eos_token_id if tokenizer.eos_token_id is not None else tokenizer.sep_token_id
    else:
        vocab_size = decoder_config_dict.get("vocab_size", 50368)
        pad_token_id = decoder_config_dict.get("pad_token_id", 50283)
        bos_token_id = decoder_config_dict.get("bos_token_id", 50281)
        eos_token_id = decoder_config_dict.get("eos_token_id", 50282)

    # Get encoder hidden size from model
    encoder_hidden_size = model.config.hidden_size if hasattr(model.config, 'hidden_size') else 768

    # Create GPT-2 decoder config
    gpt2_config = GPT2DecoderConfig(
        gpt2_model_name=decoder_config_dict.get("gpt2_model_name", "gpt2-medium"),
        encoder_hidden_size=encoder_hidden_size,
        projection_hidden_size=decoder_config_dict.get("projection_hidden_size", 1024),
        use_prefix_injection=decoder_config_dict.get("use_prefix_injection", True),
        num_prefix_tokens=decoder_config_dict.get("num_prefix_tokens", None),
        prefix_projection_layers=decoder_config_dict.get("prefix_projection_layers", 1),
        freeze_layers=decoder_config_dict.get("freeze_layers", 0),
        dropout=decoder_config_dict.get("dropout", 0.1),
        max_position_embeddings=decoder_config_dict.get("max_position_embeddings", 512),
        vocab_size=vocab_size,
        pad_token_id=pad_token_id,
        bos_token_id=bos_token_id,
        eos_token_id=eos_token_id,
        generation_max_length=decoder_config_dict.get("generation_max_length", 128),
        temperature=decoder_config_dict.get("temperature", 1.0),
        top_k=decoder_config_dict.get("top_k", 50),
        top_p=decoder_config_dict.get("top_p", 0.9),
        repetition_penalty=decoder_config_dict.get("repetition_penalty", 1.2),
    )

    logger.info("=" * 60)
    logger.info("Initializing GPT2DecoderHead (edge-friendly)")
    logger.info("=" * 60)
    logger.info(f"  GPT-2 model: {gpt2_config.gpt2_model_name}")
    logger.info(f"  Encoder hidden: {encoder_hidden_size} -> Projection: {gpt2_config.projection_hidden_size}")
    logger.info(f"  Freeze layers: {gpt2_config.freeze_layers}")
    logger.info(f"  Vocab size: {gpt2_config.vocab_size}")
    logger.info(f"  BOS/EOS/PAD: {gpt2_config.bos_token_id}/{gpt2_config.eos_token_id}/{gpt2_config.pad_token_id}")
    logger.info(f"  Estimated VRAM: {gpt2_config.get_estimated_vram_gb():.2f} GB")
    logger.info("=" * 60)

    # Create decoder head
    decoder_head = GPT2DecoderHead(
        config=gpt2_config,
        encoder_hidden_size=encoder_hidden_size,
    )

    # Log decoder params
    decoder_params = sum(p.numel() for p in decoder_head.parameters())
    trainable_params = sum(p.numel() for p in decoder_head.parameters() if p.requires_grad)
    logger.info(f"GPT-2 decoder total params: {decoder_params:,}")
    logger.info(f"GPT-2 decoder trainable params: {trainable_params:,}")

    # Add to model
    model.heads["counterfactual"] = decoder_head

    # Register capability
    if hasattr(model, "capabilities"):
        from modeling_studio.data.labels import Capability
        if Capability.COUNTERFACTUAL not in model.capabilities:
            model.capabilities.append(Capability.COUNTERFACTUAL)

    return model


def _initialize_moe_decoder(
    model,
    config: dict[str, Any],
    tokenizer=None,
):
    """
    Initialize MoE-based decoder head (original architecture).

    This is the ~420M parameter decoder with 8 experts. Requires
    substantial training data (Chinchilla: ~8B tokens).
    """
    from modeling_studio.data.labels import Capability
    from modeling_studio.models.decoder_config import DecoderMoEConfig
    from modeling_studio.models.decoder_moe import CounterfactualDecoderHead

    decoder_config_dict = config.get("decoder", {})

    # Get vocab size from tokenizer if available
    if tokenizer is not None:
        vocab_size = len(tokenizer)
        pad_token_id = tokenizer.pad_token_id if tokenizer.pad_token_id is not None else 0
        # Use CLS token as BOS, SEP as EOS if not explicitly defined
        bos_token_id = tokenizer.bos_token_id if tokenizer.bos_token_id is not None else tokenizer.cls_token_id
        eos_token_id = tokenizer.eos_token_id if tokenizer.eos_token_id is not None else tokenizer.sep_token_id
    else:
        vocab_size = decoder_config_dict.get("vocab_size", 50368)
        pad_token_id = decoder_config_dict.get("pad_token_id", 50283)
        bos_token_id = decoder_config_dict.get("bos_token_id", 50281)  # CLS
        eos_token_id = decoder_config_dict.get("eos_token_id", 50282)  # SEP

    # Get num_layers to set default dense/moe layers
    num_layers = decoder_config_dict.get("num_layers", 8)
    hidden_size = decoder_config_dict.get("hidden_size", 1280)

    # Default layer assignments (2 dense + rest MoE)
    default_dense = tuple(range(min(2, num_layers)))
    default_moe = tuple(range(min(2, num_layers), num_layers))

    # Parse dense_layers and moe_layers from config
    dense_layers = decoder_config_dict.get("dense_layers", list(default_dense))
    moe_layers = decoder_config_dict.get("moe_layers", list(default_moe))
    if isinstance(dense_layers, list):
        dense_layers = tuple(dense_layers)
    if isinstance(moe_layers, list):
        moe_layers = tuple(moe_layers)

    # Create decoder config from YAML settings
    decoder_config = DecoderMoEConfig(
        hidden_size=hidden_size,
        num_layers=num_layers,
        vocab_size=vocab_size,
        pad_token_id=pad_token_id,
        bos_token_id=bos_token_id,
        eos_token_id=eos_token_id,
        max_position_embeddings=decoder_config_dict.get("max_position_embeddings", 512),
        num_attention_heads=decoder_config_dict.get("num_attention_heads", 20),
        num_kv_heads=decoder_config_dict.get("num_kv_heads", 4),
        head_dim=decoder_config_dict.get("head_dim", 64),
        dense_layers=dense_layers,
        moe_layers=moe_layers,
        dense_intermediate_size=decoder_config_dict.get("intermediate_size", int(hidden_size * 2.8)),
        num_experts=decoder_config_dict.get("num_experts", 8),
        num_experts_per_token=decoder_config_dict.get("num_experts_per_token", 2),
        expert_intermediate_size=decoder_config_dict.get("expert_intermediate_size", int(hidden_size * 1.6)),
        use_shared_expert=decoder_config_dict.get("use_shared_expert", True),
        shared_expert_intermediate_size=decoder_config_dict.get("shared_expert_intermediate_size", hidden_size),
        capacity_factor=decoder_config_dict.get("capacity_factor", 1.5),
        load_balancing_loss_weight=decoder_config_dict.get("load_balancing_loss_weight", 0.01),
        router_z_loss_weight=decoder_config_dict.get("router_z_loss_weight", 0.001),
        hidden_dropout=decoder_config_dict.get("hidden_dropout", 0.1),
        attention_dropout=decoder_config_dict.get("attention_dropout", 0.1),
    )

    logger.info("=" * 60)
    logger.info("Initializing CounterfactualDecoderHead")
    logger.info("=" * 60)
    logger.info(f"  Hidden size: {decoder_config.hidden_size}")
    logger.info(f"  Vocab size: {decoder_config.vocab_size}")
    logger.info(f"  Num layers: {decoder_config.num_layers}")
    logger.info(f"  Attention heads: {decoder_config.num_attention_heads} (KV: {decoder_config.num_kv_heads})")
    logger.info(f"  Experts: {decoder_config.num_experts} (top-{decoder_config.num_experts_per_token})")
    logger.info(f"  Shared expert: {decoder_config.use_shared_expert}")
    logger.info(f"  BOS/EOS/PAD: {decoder_config.bos_token_id}/{decoder_config.eos_token_id}/{decoder_config.pad_token_id}")
    logger.info("=" * 60)

    # Get encoder hidden size from model config
    encoder_hidden_size = model.config.hidden_size if hasattr(model.config, 'hidden_size') else 768

    # Create decoder head
    decoder_head = CounterfactualDecoderHead(
        config=decoder_config,
        encoder_hidden_size=encoder_hidden_size,
    )

    # Log decoder params
    decoder_params = sum(p.numel() for p in decoder_head.parameters())
    logger.info(f"Decoder head params: {decoder_params:,}")

    # Add to model
    model.heads["counterfactual"] = decoder_head

    # Register capability
    if hasattr(model, "capabilities"):
        from modeling_studio.data.labels import Capability
        if Capability.COUNTERFACTUAL not in model.capabilities:
            model.capabilities.append(Capability.COUNTERFACTUAL)

    return model


def init_tokenizer(config: dict[str, Any]) -> AutoTokenizer:
    """Initialize tokenizer from config or model checkpoint."""
    model_config = config.get("model", {})
    checkpoint_path = model_config.get("checkpoint_path")

    # Try to load tokenizer from checkpoint
    if checkpoint_path:
        tokenizer_path = Path(checkpoint_path)
        if (tokenizer_path / "tokenizer.json").exists() or (tokenizer_path / "tokenizer_config.json").exists():
            tokenizer = AutoTokenizer.from_pretrained(str(tokenizer_path), trust_remote_code=True)
            logger.info(f"Loaded tokenizer from {checkpoint_path}")
            return tokenizer

    # Fall back to ModernBERT tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
        "answerdotai/ModernBERT-base",
        trust_remote_code=True,
    )
    logger.info("Loaded ModernBERT tokenizer")

    # Ensure padding token is set
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    return tokenizer


# =============================================================================
# Dataset Loading
# =============================================================================


def load_datasets(
    config: dict[str, Any],
    tokenizer: AutoTokenizer,
    debug: bool = False,
):
    """
    Load counterfactual datasets for training.

    Args:
        config: Configuration dictionary
        tokenizer: Tokenizer for encoding counterfactual text
        debug: If True, use small subset for testing

    Returns:
        Tuple of (train_dataset, eval_dataset)
    """
    from modeling_studio.data.loaders import load_counterfactual_dataset

    data_config = config.get("data", {})
    train_path = data_config.get("train_path", "data/counterfactual/training")
    mode = data_config.get("embeddings_mode", "precomputed")
    max_input_length = data_config.get("max_input_length", 256)
    max_output_length = data_config.get("max_output_length", 256)
    load_to_ram = data_config.get("load_to_ram", False)
    full_sequence = data_config.get("full_sequence", True)  # Default to full sequence

    logger.info(f"Loading counterfactual dataset from {train_path}")
    logger.info(f"  Mode: {mode}")
    logger.info(f"  Full sequence: {full_sequence}")
    logger.info(f"  Max input length: {max_input_length}")
    logger.info(f"  Max output length: {max_output_length}")
    logger.info(f"  Load to RAM: {load_to_ram}")

    # Load train dataset
    train_dataset = load_counterfactual_dataset(
        data_dir=train_path,
        tokenizer=tokenizer,
        mode=mode,
        split="train",
        max_input_length=max_input_length,
        max_output_length=max_output_length,
        load_to_ram=load_to_ram,
        full_sequence=full_sequence,
    )

    # Load validation dataset
    eval_dataset = load_counterfactual_dataset(
        data_dir=train_path,
        tokenizer=tokenizer,
        mode=mode,
        split="val",
        max_input_length=max_input_length,
        max_output_length=max_output_length,
        load_to_ram=load_to_ram,
        full_sequence=full_sequence,
    )

    # Debug mode: use tiny subsets
    if debug:
        logger.info("DEBUG MODE: Using tiny dataset subsets")
        from modeling_studio.data.counterfactual_dataset import CounterfactualSubset
        train_dataset = CounterfactualSubset(train_dataset, list(range(min(100, len(train_dataset)))))
        eval_dataset = CounterfactualSubset(eval_dataset, list(range(min(50, len(eval_dataset)))))

    logger.info(f"Train samples: {len(train_dataset):,}")
    logger.info(f"Eval samples: {len(eval_dataset):,}")

    return train_dataset, eval_dataset


# =============================================================================
# Evaluation Callbacks
# =============================================================================


def _create_eval_callbacks(
    config: dict[str, Any],
    tokenizer: AutoTokenizer,
    eval_dataset,
    debug: bool = False,
) -> list:
    """
    Create evaluation callbacks for decoder training.

    Callbacks:
        1. GenerationEvalCallback: Runs counterfactual quality metrics
           (completion rate, format adherence, context fidelity)
        2. PerplexityCallback: Logs perplexity during evaluation

    Args:
        config: Training configuration
        tokenizer: Tokenizer for decoding
        eval_dataset: Evaluation dataset for sampling
        debug: Debug mode (fewer samples)

    Returns:
        List of TrainerCallback instances
    """
    from modeling_studio.trainers.decoder_trainer import GenerationEvalCallback

    callbacks = []
    eval_config = config.get("evaluation", {})

    # Extract eval samples for generation quality evaluation
    eval_samples = _extract_eval_samples(
        eval_dataset=eval_dataset,
        tokenizer=tokenizer,
        num_samples=eval_config.get("num_gen_samples", 50 if not debug else 10),
    )

    if eval_samples:
        # GenerationEvalCallback for counterfactual quality metrics
        gen_callback = GenerationEvalCallback(
            tokenizer=tokenizer,
            eval_samples=eval_samples,
            valence=eval_config.get("valence", "positive"),
            eval_every_n_steps=eval_config.get("gen_eval_steps", 500 if not debug else 50),
            max_new_tokens=eval_config.get("max_new_tokens", 64),
            num_samples=eval_config.get("num_gen_samples", 50 if not debug else 10),
            temperature=eval_config.get("temperature", 0.7),
        )
        callbacks.append(gen_callback)
        logger.info(f"Added GenerationEvalCallback with {len(eval_samples)} samples")
    else:
        logger.warning("No eval samples available for GenerationEvalCallback")

    # Add PerplexityLoggingCallback
    ppl_callback = _create_perplexity_callback(config, debug)
    if ppl_callback:
        callbacks.append(ppl_callback)
        logger.info("Added PerplexityLoggingCallback")

    # Add BLEU/ROUGE/Distinct-N callback if enabled
    if eval_config.get("compute_bleu", False) or eval_config.get("compute_rouge", False) or eval_config.get("compute_distinct_n", False):
        text_metrics_callback = _create_text_metrics_callback(
            config=config,
            tokenizer=tokenizer,
            eval_samples=eval_samples,
            debug=debug,
        )
        if text_metrics_callback:
            callbacks.append(text_metrics_callback)
            logger.info("Added TextMetricsCallback (BLEU/ROUGE/Distinct-N)")

    # Add expert utilization callback for MoE debugging
    if eval_config.get("log_expert_utilization", False):
        expert_callback = _create_expert_utilization_callback(
            config=config,
            debug=debug,
        )
        if expert_callback:
            callbacks.append(expert_callback)
            logger.info("Added ExpertUtilizationCallback")

    return callbacks


def _extract_eval_samples(
    eval_dataset,
    tokenizer: AutoTokenizer,
    num_samples: int = 50,
) -> list[tuple[str, str]]:
    """
    Extract (input_text, reference_text) pairs from eval dataset.

    Args:
        eval_dataset: Evaluation dataset (CounterfactualDataset)
        tokenizer: Tokenizer for decoding
        num_samples: Number of samples to extract

    Returns:
        List of (input_text, reference_text) tuples
    """
    samples_list = []
    num_samples = min(num_samples, len(eval_dataset))

    # CounterfactualDataset stores raw samples with text in .samples attribute
    # The __getitem__ only returns tensors, so we need to access .samples directly
    raw_samples = getattr(eval_dataset, "samples", None)
    indices = getattr(eval_dataset, "indices", None)

    if raw_samples is not None and indices is not None:
        # Direct access to raw samples (preferred for CounterfactualDataset)
        for i in range(num_samples):
            try:
                sample_idx = indices[i]
                sample = raw_samples[sample_idx]

                input_text = sample.get("input_text") or sample.get("context") or sample.get("source")
                reference_text = (
                    sample.get("counterfactual_full_text")
                    or sample.get("counterfactual")
                    or sample.get("output_text")
                    or sample.get("target")
                )

                if input_text and reference_text:
                    samples_list.append((input_text, reference_text))

            except Exception as e:
                logger.debug(f"Failed to extract sample {i} from raw samples: {e}")
                continue
    else:
        # Fallback: Try to extract from __getitem__ output
        for i in range(num_samples):
            try:
                item = eval_dataset[i]

                input_text = None
                reference_text = None

                # Try common key names for input
                for key in ["input_text", "input", "context", "source"]:
                    if key in item and isinstance(item[key], str):
                        input_text = item[key]
                        break

                # Try common key names for reference
                for key in ["output_text", "output", "target", "counterfactual", "counterfactual_full_text", "reference"]:
                    if key in item and isinstance(item[key], str):
                        reference_text = item[key]
                        break

                # If text not directly available, decode from token IDs
                if input_text is None and "decoder_input_ids" in item:
                    # For counterfactual dataset, input is encoder embeddings
                    # We can't easily recover text, skip
                    pass

                if reference_text is None and "labels" in item:
                    labels = item["labels"]
                    if hasattr(labels, "tolist"):
                        labels = labels.tolist()
                    # Filter out -100 padding
                    valid_labels = [l for l in labels if l != -100]
                    if valid_labels:
                        reference_text = tokenizer.decode(valid_labels, skip_special_tokens=True)

                # For input_text, try decoding decoder_input_ids as a proxy
                if input_text is None and reference_text is not None and "decoder_input_ids" in item:
                    # Use reference as both (won't compute meaningful BLEU but at least callback runs)
                    input_text = reference_text[:100]  # Truncate as pseudo-input

                if input_text and reference_text:
                    samples_list.append((input_text, reference_text))

            except Exception as e:
                logger.debug(f"Failed to extract sample {i}: {e}")
                continue

    logger.info(f"Extracted {len(samples_list)} eval samples for generation quality")
    return samples_list


def _create_perplexity_callback(config: dict[str, Any], debug: bool = False):
    """
    Create a callback that logs perplexity metrics during evaluation.

    Returns:
        PerplexityLoggingCallback or None if creation fails
    """
    from transformers import TrainerCallback, TrainerControl, TrainerState, TrainingArguments

    class PerplexityLoggingCallback(TrainerCallback):
        """Callback to compute and log perplexity during evaluation."""

        def on_evaluate(
            self,
            args: TrainingArguments,
            state: TrainerState,
            control: TrainerControl,
            metrics: dict[str, float] | None = None,
            **kwargs,
        ) -> TrainerControl:
            """Log perplexity from eval_loss."""
            if metrics and "eval_loss" in metrics:
                import math
                eval_loss = metrics["eval_loss"]
                perplexity = math.exp(eval_loss) if eval_loss < 100 else float("inf")
                logger.info(f"[Perplexity] Step {state.global_step}: {perplexity:.4f}")

                # Log to wandb if available
                if state.is_world_process_zero:
                    try:
                        import wandb
                        if wandb.run is not None:
                            wandb.log({
                                "eval/perplexity": perplexity,
                                "eval/step": state.global_step,
                            })
                    except ImportError:
                        pass

            return control

    return PerplexityLoggingCallback()


def _create_text_metrics_callback(
    config: dict[str, Any],
    tokenizer: AutoTokenizer,
    eval_samples: list[tuple[str, str]],
    debug: bool = False,
):
    """
    Create callback for BLEU, ROUGE, and Distinct-N metrics.

    These metrics are computed on generated text vs references during evaluation.
    """
    from transformers import TrainerCallback, TrainerControl, TrainerState, TrainingArguments

    eval_config = config.get("evaluation", {})
    compute_bleu = eval_config.get("compute_bleu", True)
    compute_rouge = eval_config.get("compute_rouge", True)
    compute_distinct = eval_config.get("compute_distinct_n", True)

    class TextMetricsCallback(TrainerCallback):
        """Callback to compute BLEU, ROUGE, Distinct-N on generated text."""

        def __init__(self):
            self.eval_samples = eval_samples
            self.tokenizer = tokenizer
            self._last_eval_step = -1

        def on_evaluate(
            self,
            args: TrainingArguments,
            state: TrainerState,
            control: TrainerControl,
            model=None,
            **kwargs,
        ) -> TrainerControl:
            """Compute text metrics during evaluation."""
            if model is None or not self.eval_samples:
                return control

            # Avoid duplicate computation
            if state.global_step == self._last_eval_step:
                return control
            self._last_eval_step = state.global_step

            try:
                predictions, references = self._generate_predictions(model, state)

                if not predictions:
                    return control

                metrics = {}

                # BLEU
                if compute_bleu:
                    try:
                        from modeling_studio.evaluation.decoder_metrics import compute_bleu as calc_bleu
                        bleu = calc_bleu(predictions, references)
                        metrics["text_metrics/bleu"] = bleu
                        logger.info(f"[TextMetrics] BLEU: {bleu:.2f}")
                    except Exception as e:
                        logger.warning(f"BLEU computation failed: {e}")

                # ROUGE
                if compute_rouge:
                    try:
                        from modeling_studio.evaluation.decoder_metrics import compute_rouge as calc_rouge
                        rouge = calc_rouge(predictions, references)
                        for key, value in rouge.items():
                            metrics[f"text_metrics/{key}"] = value
                        logger.info(f"[TextMetrics] ROUGE-L: {rouge.get('rougeL', 0):.4f}")
                    except Exception as e:
                        logger.warning(f"ROUGE computation failed: {e}")

                # Distinct-N
                if compute_distinct:
                    try:
                        from modeling_studio.evaluation.decoder_metrics import compute_distinct_n
                        distinct = compute_distinct_n(predictions)
                        for key, value in distinct.items():
                            metrics[f"text_metrics/{key}"] = value
                        logger.info(f"[TextMetrics] Distinct-2: {distinct.get('distinct-2', 0):.4f}")
                    except Exception as e:
                        logger.warning(f"Distinct-N computation failed: {e}")

                # Log to wandb
                if metrics and state.is_world_process_zero:
                    try:
                        import wandb
                        if wandb.run is not None:
                            metrics["text_metrics/step"] = state.global_step
                            wandb.log(metrics)
                    except ImportError:
                        pass

            except Exception as e:
                logger.warning(f"TextMetricsCallback error: {e}")

            return control

        def _generate_predictions(self, model, state) -> tuple[list[str], list[str]]:
            """Generate predictions for eval samples."""
            import torch

            model.eval()
            device = next(model.parameters()).device
            predictions = []
            references = []

            # Get decoder head
            if hasattr(model, "heads") and "counterfactual" in model.heads:
                decoder_head = model.heads["counterfactual"]
            elif hasattr(model, "decoder"):
                decoder_head = model.decoder
            else:
                decoder_head = model

            num_samples = min(20 if not debug else 5, len(self.eval_samples))

            with torch.no_grad():
                for input_text, ref_text in self.eval_samples[:num_samples]:
                    try:
                        encoded = self.tokenizer(
                            input_text,
                            return_tensors="pt",
                            truncation=True,
                            max_length=256,
                            padding=True,
                        )
                        input_ids = encoded["input_ids"].to(device)

                        if hasattr(decoder_head, "generate"):
                            output_ids = decoder_head.generate(
                                input_ids=input_ids,
                                max_new_tokens=64,
                                temperature=0.7,
                                do_sample=True,
                            )
                            pred_text = self.tokenizer.decode(
                                output_ids[0], skip_special_tokens=True
                            )
                            predictions.append(pred_text)
                            references.append(ref_text)
                    except Exception as e:
                        logger.debug(f"Generation failed: {e}")
                        continue

            model.train()
            return predictions, references

    return TextMetricsCallback()


def _create_expert_utilization_callback(
    config: dict[str, Any],
    debug: bool = False,
):
    """
    Create callback for logging MoE expert utilization stats.

    Tracks load balancing across experts to detect expert collapse.
    """
    from transformers import TrainerCallback, TrainerControl, TrainerState, TrainingArguments

    eval_config = config.get("evaluation", {})
    log_steps = eval_config.get("expert_util_steps", 1000 if not debug else 100)

    class ExpertUtilizationCallback(TrainerCallback):
        """Callback to log MoE expert utilization statistics."""

        def __init__(self):
            self._last_log_step = 0

        def on_step_end(
            self,
            args: TrainingArguments,
            state: TrainerState,
            control: TrainerControl,
            model=None,
            **kwargs,
        ) -> TrainerControl:
            """Log expert utilization stats periodically."""
            if model is None:
                return control

            steps_since_log = state.global_step - self._last_log_step
            if steps_since_log < log_steps:
                return control

            self._last_log_step = state.global_step

            try:
                # Get decoder head
                if hasattr(model, "heads") and "counterfactual" in model.heads:
                    decoder_head = model.heads["counterfactual"]
                elif hasattr(model, "decoder"):
                    decoder_head = model.decoder
                else:
                    return control

                # Check if MoE decoder with expert tracking
                if not hasattr(decoder_head, "get_expert_utilization"):
                    return control

                util_stats = decoder_head.get_expert_utilization()

                if util_stats:
                    logger.info(f"[ExpertUtil] Step {state.global_step}:")
                    for layer_idx, stats in util_stats.items():
                        avg_util = sum(stats.values()) / len(stats) if stats else 0
                        min_util = min(stats.values()) if stats else 0
                        max_util = max(stats.values()) if stats else 0
                        logger.info(f"  Layer {layer_idx}: avg={avg_util:.3f}, min={min_util:.3f}, max={max_util:.3f}")

                    # Log to wandb
                    if state.is_world_process_zero:
                        try:
                            import wandb
                            if wandb.run is not None:
                                wandb_metrics = {"expert_util/step": state.global_step}
                                for layer_idx, stats in util_stats.items():
                                    for expert_id, util in stats.items():
                                        wandb_metrics[f"expert_util/layer{layer_idx}_expert{expert_id}"] = util
                                wandb.log(wandb_metrics)
                        except ImportError:
                            pass

            except Exception as e:
                logger.debug(f"Expert utilization logging failed: {e}")

            return control

    return ExpertUtilizationCallback()


# =============================================================================
# Training Arguments
# =============================================================================


def create_training_args(
    config: dict[str, Any],
    output_dir: str | None = None,
    debug: bool = False,
) -> TrainingArguments:
    """Create training arguments from config."""
    training_config = config.get("training", {})

    # Determine output directory
    if output_dir is None:
        output_dir = training_config.get("checkpoint_dir", "checkpoints/ultrabert-gen-decoder-v1")

    # Check bf16 support
    bf16_supported = torch.cuda.is_available() and torch.cuda.is_bf16_supported()
    bf16_config = training_config.get("bf16", True)
    fp16_config = training_config.get("fp16", False)

    if bf16_config and not bf16_supported:
        logger.warning("bf16 not supported, falling back to fp16")
        bf16_config = False
        fp16_config = True

    # Get batch sizes
    train_batch_size = training_config.get("per_device_train_batch_size", 8)
    eval_batch_size = training_config.get("per_device_eval_batch_size", 16)
    gradient_checkpointing = training_config.get("gradient_checkpointing", True)

    # Dataloader settings
    dataloader_num_workers = training_config.get("num_workers", 4)

    # Debug mode adjustments
    if debug:
        train_batch_size = min(train_batch_size, 4)
        eval_batch_size = min(eval_batch_size, 8)
        gradient_checkpointing = True
        dataloader_num_workers = 0
        training_config["num_train_epochs"] = 1
        training_config["save_steps"] = 50
        training_config["eval_steps"] = 50
        training_config["logging_steps"] = 10
        logger.info(f"Debug: batch_size={train_batch_size}, epochs=1")

    # Build training arguments
    # Note: load_best_model_at_end=True causes double GPU memory usage as Trainer
    # loads checkpoint weights again. Default to False for memory efficiency.
    load_best_model = training_config.get("load_best_model_at_end", False)

    args = TrainingArguments(
        output_dir=output_dir,
        # Optimization
        learning_rate=float(training_config.get("learning_rate", 2e-4)),
        weight_decay=float(training_config.get("weight_decay", 0.01)),
        max_grad_norm=float(training_config.get("max_grad_norm", 1.0)),
        optim=training_config.get("optim", "adamw_torch_fused"),
        # Schedule
        lr_scheduler_type=training_config.get("lr_scheduler_type", "cosine"),
        warmup_ratio=float(training_config.get("warmup_ratio", 0.1)),
        # Training duration
        num_train_epochs=int(training_config.get("num_train_epochs", 10)),
        max_steps=int(training_config.get("max_steps", -1)),
        # Batch sizes
        per_device_train_batch_size=train_batch_size,
        per_device_eval_batch_size=eval_batch_size,
        gradient_accumulation_steps=int(training_config.get("gradient_accumulation_steps", 4)),
        # Mixed precision
        bf16=bf16_config,
        fp16=fp16_config,
        # Memory optimization
        gradient_checkpointing=gradient_checkpointing,
        # Checkpointing (critical for Colab)
        save_strategy=training_config.get("save_strategy", "steps"),
        save_steps=int(training_config.get("save_steps", 500)),
        save_total_limit=int(training_config.get("save_total_limit", 5)),
        save_safetensors=training_config.get("save_safetensors", True),
        # Evaluation
        eval_strategy=training_config.get("eval_strategy", "steps"),
        eval_steps=int(training_config.get("eval_steps", 500)),
        # Logging
        logging_strategy=training_config.get("logging_strategy", "steps"),
        logging_steps=int(training_config.get("logging_steps", 50)),
        logging_first_step=training_config.get("logging_first_step", True),
        # Best model - disabled by default to prevent double GPU memory usage
        load_best_model_at_end=load_best_model,
        metric_for_best_model=training_config.get("metric_for_best_model", "eval_loss"),
        greater_is_better=training_config.get("greater_is_better", False),
        # Reporting
        report_to=training_config.get("report_to", ["tensorboard"]),
        # Seed
        seed=int(training_config.get("seed", 42)),
        # Dataloader
        dataloader_num_workers=dataloader_num_workers,
        dataloader_pin_memory=training_config.get("dataloader_pin_memory", True),
        dataloader_prefetch_factor=2 if dataloader_num_workers > 0 else None,
        # Remove unused columns warning
        remove_unused_columns=False,
    )

    return args


# =============================================================================
# Save Utilities
# =============================================================================


def save_model_and_artifacts(
    model,
    tokenizer,
    output_dir: str | Path,
    config: dict[str, Any],
    training_args: TrainingArguments,
    eval_results: dict[str, float] | None = None,
):
    """Save final model and training artifacts."""
    import gc
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    logger.info(f"Saving model and artifacts to {output_dir}")

    # Free up memory before saving
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    # Move model to CPU for saving to avoid GPU memory issues
    model_device = next(model.parameters()).device
    model.cpu()
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    # Save model - use pytorch format to avoid safetensors memory issues
    try:
        model.save_pretrained(output_dir, safe_serialization=False)
    except Exception as e:
        logger.warning(f"Standard save failed: {e}, trying state_dict save")
        torch.save(model.state_dict(), output_dir / "pytorch_model.bin")
        model.config.save_pretrained(output_dir)
    finally:
        # Move model back to original device
        model.to(model_device)

    logger.info("  - Model saved")

    # Save tokenizer
    tokenizer.save_pretrained(output_dir)
    logger.info("  - Tokenizer saved")

    # Save config
    with open(output_dir / "training_config.yaml", "w") as f:
        yaml.dump(config, f, default_flow_style=False)
    logger.info("  - Training config saved")

    # Save training args
    with open(output_dir / "training_args.json", "w") as f:
        json.dump(training_args.to_dict(), f, indent=2)
    logger.info("  - Training args saved")

    # Save eval results
    if eval_results:
        with open(output_dir / "eval_results.json", "w") as f:
            json.dump(eval_results, f, indent=2)
        logger.info("  - Eval results saved")

    # Save completion marker
    with open(output_dir / "training_complete.json", "w") as f:
        json.dump({
            "completed_at": datetime.now().isoformat(),
            "final_eval_loss": eval_results.get("eval_loss") if eval_results else None,
        }, f, indent=2)

    logger.info("Model and artifacts saved successfully!")


# =============================================================================
# Main Training Function
# =============================================================================


def train(
    config: dict[str, Any],
    args: argparse.Namespace,
) -> dict[str, float]:
    """Run the full Stage C training pipeline."""
    global _TRAINER_INSTANCE

    # Set seed
    seed = args.seed if args.seed else config.get("training", {}).get("seed", 42)
    set_seed(seed)
    logger.info(f"Random seed: {seed}")

    # Determine device
    device = "cuda" if torch.cuda.is_available() else "cpu"
    logger.info(f"Device: {device}")

    if device == "cuda":
        logger.info(f"  GPU: {torch.cuda.get_device_name(0)}")
        logger.info(f"  Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

    # Initialize tokenizer
    tokenizer = init_tokenizer(config)

    # Load base model (already on device from load_checkpoint)
    model = load_base_model(config, device=device)

    # Initialize decoder head (pass tokenizer for vocab_size and special tokens)
    model = initialize_decoder_head(model, config, tokenizer=tokenizer)

    # Note: model is already on device from load_base_model, no need to call .to(device) again

    # Freeze encoder and existing heads
    from modeling_studio.trainers.decoder_trainer import freeze_encoder_and_heads
    model_config = config.get("model", {})
    freeze_encoder_and_heads(
        model,
        freeze_encoder=model_config.get("freeze_encoder", True),
        freeze_heads=model_config.get("freeze_existing_heads", True),
        decoder_head_name="counterfactual",
    )

    # Load datasets
    train_dataset, eval_dataset = load_datasets(config, tokenizer, debug=args.debug)

    # Create data collator
    from modeling_studio.trainers.decoder_collator import CounterfactualCollator
    data_collator = CounterfactualCollator(
        tokenizer=tokenizer,
        max_output_length=config.get("data", {}).get("max_output_length", 256),
    )

    # Dry run: validate without training
    if args.dry_run:
        logger.info("Dry run complete - config and data validated successfully")
        return {}

    # Create training arguments
    checkpoint_dir = args.checkpoint_dir or config.get("training", {}).get(
        "checkpoint_dir", "checkpoints/ultrabert-gen-decoder-v1"
    )
    output_dir = args.output_dir or config.get("training", {}).get(
        "output_dir", "outputs/ultrabert-gen-decoder-v1"
    )

    training_args = create_training_args(
        config=config,
        output_dir=checkpoint_dir,
        debug=args.debug,
    )

    # Create trainer
    from modeling_studio.trainers.decoder_trainer import DecoderTrainer, GenerationEvalCallback

    decoder_config = config.get("decoder", {})
    aux_loss_weight = decoder_config.get("load_balancing_loss_weight", 0.01) + \
                      decoder_config.get("router_z_loss_weight", 0.001)

    # Create evaluation callbacks
    callbacks = _create_eval_callbacks(
        config=config,
        tokenizer=tokenizer,
        eval_dataset=eval_dataset,
        debug=args.debug,
    )

    trainer = DecoderTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        data_collator=data_collator,
        tokenizer=tokenizer,
        aux_loss_weight=aux_loss_weight,
        callbacks=callbacks,
    )

    # Store trainer for signal handler
    _TRAINER_INSTANCE = trainer

    # Determine resume checkpoint
    resume_checkpoint = args.resume_from_checkpoint
    if args.auto_resume and resume_checkpoint is None:
        resume_checkpoint = find_latest_checkpoint(checkpoint_dir)
        if resume_checkpoint:
            logger.info(f"Auto-resuming from: {resume_checkpoint}")

    # Log training info
    logger.info("=" * 60)
    logger.info("Starting Stage C Training: Counterfactual MoE Decoder")
    logger.info("=" * 60)
    logger.info(f"Checkpoint directory: {checkpoint_dir}")
    logger.info(f"Output directory: {output_dir}")
    logger.info(f"Train samples: {len(train_dataset):,}")
    logger.info(f"Eval samples: {len(eval_dataset):,}")
    logger.info(f"Effective batch size: {training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps}")
    logger.info(f"Epochs: {training_args.num_train_epochs}")
    logger.info(f"Save every: {training_args.save_steps} steps")
    if resume_checkpoint:
        logger.info(f"Resuming from: {resume_checkpoint}")
    logger.info("=" * 60)
    logger.info("Press Ctrl+C to save checkpoint and exit gracefully")
    logger.info("=" * 60)

    # Train
    train_result = trainer.train(resume_from_checkpoint=resume_checkpoint)

    # Log training results
    logger.info("Training completed!")
    logger.info(f"Training loss: {train_result.training_loss:.4f}")
    logger.info(f"Training steps: {train_result.global_step}")

    # Evaluate
    logger.info("Running final evaluation...")
    eval_results = trainer.evaluate()

    # Log eval results
    logger.info("Final evaluation results:")
    for metric, value in sorted(eval_results.items()):
        if isinstance(value, float):
            logger.info(f"  {metric}: {value:.4f}")

    # Save final model
    save_model_and_artifacts(
        model=model,
        tokenizer=tokenizer,
        output_dir=output_dir,
        config=config,
        training_args=training_args,
        eval_results=eval_results,
    )

    return eval_results


# =============================================================================
# Entry Point
# =============================================================================


def main():
    """Main entry point."""
    args = parse_args()

    # Load config
    config = load_config(args.config)

    # Apply overrides
    if args.overrides:
        config = apply_overrides(config, args.overrides)

    # Apply argument overrides
    if args.seed:
        config.setdefault("training", {})["seed"] = args.seed

    # Log configuration
    logger.info("=" * 60)
    logger.info("Stage C: Counterfactual MoE Decoder Training")
    logger.info("=" * 60)
    logger.info(f"Config: {args.config}")
    logger.info(f"Debug mode: {args.debug}")
    if args.resume_from_checkpoint:
        logger.info(f"Resume checkpoint: {args.resume_from_checkpoint}")
    if args.auto_resume:
        logger.info("Auto-resume: enabled")

    # Run training
    try:
        _eval_results = train(config, args)
        logger.info("Training completed successfully!")
        return 0
    except KeyboardInterrupt:
        logger.warning("Training interrupted - checkpoint should be saved")
        return 1
    except Exception as e:
        logger.error(f"Training failed: {e}")
        raise


if __name__ == "__main__":
    sys.exit(main())
