"""
Clean Synthetic Data - Remove Invalid Schema Labels

This script cleans the synthetic data generated by synthetic_task_generator.py
by removing labels that don't match the strict schemas.

Usage:
    python clean_synthetic_data.py --dry-run    # Preview changes
    python clean_synthetic_data.py --backup     # Create backup first
    python clean_synthetic_data.py --execute    # Apply fixes
"""

import argparse
import json
import shutil
from pathlib import Path

# Valid schemas
VALID_NER_LABELS = {
    "PERSON",
    "KINSHIP",
    "NICKNAME",
    "PET",
    "HOME_LOC",
    "FAMILY_EVENT",
    "ROUTINE",
    "TRADITION",
    "MILESTONE",
    "HEIRLOOM",
}

VALID_TEMPORAL_LABELS = {"DATE_ABS", "DATE_REL", "TIME", "DURATION", "FREQUENCY", "AGE"}

VALID_EMOTIONS = {
    "neutral",
    "joy",
    "sadness",
    "anger",
    "fear",
    "surprise",
    "love",
    "disgust",
    "admiration",
    "amusement",
    "approval",
    "caring",
    "excitement",
    "gratitude",
    "optimism",
    "pride",
    "relief",
    "contentment",
    "hope",
    "tenderness",
    "annoyance",
    "disappointment",
    "disapproval",
    "embarrassment",
    "grief",
    "nervousness",
    "remorse",
    "frustration",
    "overwhelmed",
    "emptiness",
    "nostalgia",
    "protectiveness",
    "togetherness",
    "longing",
    "warmth",
    "playfulness",
    "celebration",
    "belonging",
    "parental_pride",
    "parental_guilt",
    "patience",
    "worry",
    "bittersweet",
    "homesickness",
}

VALID_RELATIONS = {
    "no_relation",
    "parent_of",
    "child_of",
    "spouse_of",
    "sibling_of",
    "grandparent_of",
    "grandchild_of",
    "aunt_uncle_of",
    "niece_nephew_of",
    "cousin_of",
    "pet_of",
    "friend_of",
    "colleague_of",
    "lives_at",
    "owns",
}

# Directories
BASE_DIR = Path("D:/Modeling_studio")
SYNTHETIC_DIR = BASE_DIR / "data" / "familyos" / "unified" / "output_synthetic"
BACKUP_DIR = BASE_DIR / "data" / "familyos" / "unified" / "output_synthetic_backup"


class SyntheticDataCleaner:
    """Clean synthetic data by removing invalid labels."""

    def __init__(self, data_dir: Path = SYNTHETIC_DIR):
        self.data_dir = data_dir
        self.stats = {
            "total_samples": 0,
            "emotion_violations": 0,
            "ner_violations": 0,
            "temporal_violations": 0,
            "relation_violations": 0,
            "cleaned_samples": 0,
        }

    def clean_emotions(self, emotions: list) -> list:
        """Remove invalid emotions."""
        original_len = len(emotions)
        valid = [e for e in emotions if e in VALID_EMOTIONS]

        if len(valid) != original_len:
            self.stats["emotion_violations"] += original_len - len(valid)
            if not valid:
                valid = ["neutral"]  # Default if all removed

        return valid

    def clean_ner(self, ner_entities: list) -> list:
        """Remove NER entities with invalid labels."""
        original_len = len(ner_entities)
        valid = []

        for entity in ner_entities:
            label = entity.get("label", "")
            if label in VALID_NER_LABELS:
                valid.append(entity)
            else:
                self.stats["ner_violations"] += 1

        return valid

    def clean_temporal(self, temporal_entities: list) -> list:
        """Remove temporal entities with invalid labels."""
        original_len = len(temporal_entities)
        valid = []

        for entity in temporal_entities:
            label = entity.get("label", "")
            if label in VALID_TEMPORAL_LABELS:
                valid.append(entity)
            else:
                self.stats["temporal_violations"] += 1

        return valid

    def clean_relations(self, relations: list) -> list:
        """Normalize and remove invalid relations."""
        original_len = len(relations)
        valid = []

        for rel in relations:
            pred = rel.get("predicate", "")

            # Normalize common mistakes
            if pred == "nephew_niece_of":
                pred = "niece_nephew_of"
            elif pred == "owner_of":
                pred = "owns"
            elif pred == "family_of":
                self.stats["relation_violations"] += 1
                continue  # Skip generic "family_of"

            if pred in VALID_RELATIONS:
                rel["predicate"] = pred
                valid.append(rel)
            else:
                self.stats["relation_violations"] += 1

        return valid

    def clean_sample(self, sample: dict) -> dict:
        """Clean a single sample."""
        self.stats["total_samples"] += 1
        modified = False

        if "tasks" not in sample:
            return sample

        tasks = sample["tasks"]

        # Clean emotions
        if "emotions" in tasks and tasks["emotions"]:
            original = tasks["emotions"][:]
            tasks["emotions"] = self.clean_emotions(tasks["emotions"])
            if original != tasks["emotions"]:
                modified = True

        # Clean NER
        if "ner_family" in tasks and tasks["ner_family"]:
            original_len = len(tasks["ner_family"])
            tasks["ner_family"] = self.clean_ner(tasks["ner_family"])
            if len(tasks["ner_family"]) != original_len:
                modified = True

        # Clean temporal
        if "temporal" in tasks and tasks["temporal"]:
            original_len = len(tasks["temporal"])
            tasks["temporal"] = self.clean_temporal(tasks["temporal"])
            if len(tasks["temporal"]) != original_len:
                modified = True

        # Clean relations
        if "relations" in tasks and tasks["relations"]:
            original_len = len(tasks["relations"])
            tasks["relations"] = self.clean_relations(tasks["relations"])
            if len(tasks["relations"]) != original_len:
                modified = True

        if modified:
            self.stats["cleaned_samples"] += 1

        return sample

    def process_shard(self, shard_path: Path, dry_run: bool = True) -> list[dict]:
        """Process one shard file."""
        samples = []

        with open(shard_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue

                try:
                    sample = json.loads(line)
                    cleaned = self.clean_sample(sample)
                    samples.append(cleaned)
                except json.JSONDecodeError as e:
                    print(f"Error parsing line in {shard_path.name}: {e}")
                    continue

        return samples

    def run(self, dry_run: bool = True):
        """Process all shards."""
        shards = sorted(self.data_dir.glob("shard_*.jsonl"))

        if not shards:
            print(f"No shard files found in {self.data_dir}")
            return

        print(f"\n{'='*70}")
        print(f"CLEANING SYNTHETIC DATA {'(DRY RUN)' if dry_run else '(EXECUTING)'}")
        print(f"{'='*70}")
        print(f"Found {len(shards)} shard files")
        print()

        for shard_path in shards:
            print(f"Processing {shard_path.name}...", end=" ")

            cleaned_samples = self.process_shard(shard_path, dry_run)

            if not dry_run:
                # Write back cleaned samples
                with open(shard_path, "w", encoding="utf-8") as f:
                    for sample in cleaned_samples:
                        f.write(json.dumps(sample, ensure_ascii=False) + "\n")

            print(f"✓ ({len(cleaned_samples)} samples)")

        print()
        print(f"{'='*70}")
        print("SUMMARY")
        print(f"{'='*70}")
        print(f"Total samples processed: {self.stats['total_samples']:,}")
        print(f"Samples modified: {self.stats['cleaned_samples']:,}")
        print()
        print("Violations removed:")
        print(f"  - Emotions (invalid): {self.stats['emotion_violations']:,}")
        print(f"  - NER entities (invalid labels): {self.stats['ner_violations']:,}")
        print(f"  - Temporal entities (invalid labels): {self.stats['temporal_violations']:,}")
        print(f"  - Relations (invalid predicates): {self.stats['relation_violations']:,}")
        print(f"{'='*70}")

        if dry_run:
            print("\n⚠️  DRY RUN - No files modified")
            print("Run with --execute to apply changes")
        else:
            print("\n✅ Changes applied successfully!")


def create_backup():
    """Create backup of synthetic data."""
    if BACKUP_DIR.exists():
        print(f"Backup already exists at: {BACKUP_DIR}")
        response = input("Overwrite existing backup? (yes/no): ")
        if response.lower() != "yes":
            print("Backup cancelled.")
            return False
        shutil.rmtree(BACKUP_DIR)

    print(f"\nCreating backup: {SYNTHETIC_DIR} -> {BACKUP_DIR}")
    shutil.copytree(SYNTHETIC_DIR, BACKUP_DIR)

    # Count files
    backup_files = list(BACKUP_DIR.glob("shard_*.jsonl"))
    total_samples = 0
    for f in backup_files:
        with open(f, encoding="utf-8") as file:
            total_samples += sum(1 for _ in file)

    print(f"✅ Backup created: {len(backup_files)} shards, {total_samples:,} samples")
    return True


def main():
    parser = argparse.ArgumentParser(
        description="Clean synthetic data by removing invalid schema labels"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview changes without modifying files",
    )
    parser.add_argument(
        "--backup",
        action="store_true",
        help="Create backup before cleaning",
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Apply changes to files",
    )

    args = parser.parse_args()

    if not SYNTHETIC_DIR.exists():
        print(f"Error: Synthetic data directory not found: {SYNTHETIC_DIR}")
        return

    # Handle backup
    if args.backup:
        if not create_backup():
            return
        print()

    # Determine mode
    if args.execute:
        response = input("\n⚠️  This will modify files. Continue? (yes/no): ")
        if response.lower() != "yes":
            print("Cancelled.")
            return
        dry_run = False
    else:
        dry_run = True

    # Run cleaner
    cleaner = SyntheticDataCleaner()
    cleaner.run(dry_run=dry_run)

    if dry_run and not args.backup:
        print("\nNext steps:")
        print("  1. python clean_synthetic_data.py --backup     # Create backup")
        print("  2. python clean_synthetic_data.py --execute    # Apply fixes")


if __name__ == "__main__":
    main()
